print ('Привет')
print ('Как тебя зовут?')
name = input()
print ('Приятно познакомиться')
print ('Как твои дела?')
print ('У меня тоже все хорошо')
print ('Прощай')
print ('Вам понравилось?')
raiting = input()
print ('Ваша оценка:' + raiting)
print ('Помочь?')
helping = input()