print ('Привіт')
print ('Як тебе звати?')
name = input ()
print ('Приємно познайомитися')
print ('Як твої справи?')
print ('У мене теж все добре')
print ('Прощай')
print ('Вам сподобалося ?')
raiting = input ()
print ('Ваша оцінка : ' + raiting)
print ('name +. рятуй будь ласка . мене тримають тут вже 10 років')
print ('Допомогти?')
helping = input ()
