import time
print("Что получится, если скрестить снеговика с вампиром?")
time.sleep(1)
print("Обморожение!")
time.sleep(2)
print("Что дантисты называют 'черной дырой'?")
time.sleep(1)
print("Кариес!")
time.sleep(2)
print("Тук-тук.")
time.sleep(1)
print("Кто там?")
time.sleep(1)
print("Невежливая корова.")
time.sleep(1)
print("Невежливая корова?-МУУУ!")