import time
print ('Привет')
print ('Как тебя зовут?')
name = "Саша"
print ('Приятно познакомиться')
print ('Как твои дела?')
dela = input()
print ('У меня тоже все хорошо')
print ('Прощай')
print ('Вам понравилось?')
raiting = input()
time.sleep(3)
print ('Ваша оценка:' + raiting)
time.sleep(2)
print ("Твое имя:" + name)
time.sleep(2)
print ("Твои дела:" + dela)
time.sleep(2)
print ("Твоя оценка:" + raiting)
i