import time
print ("Привіт")
time.sleep(1)
print("Вкажи ім'я")
name = input()
if name == "Ксюша" or name == "Оксана" or name == "Ксенія" or name == "Сюся":
    print("Знай! ти найкраща людина у світі мого творця")
    time.sleep(1)
    print("Коротко що він сказав про тебе")
    time.sleep(1)
    print("Пунктуальність : 100%")
    time.sleep(1)
    print("Щирість : 100%")
    time.sleep(1)
    print("Дата народження: 07.12.2004")
    time.sleep(1)
    print("Ти найкраща!!!")
elif name == "Юрій" or name == "Юра":
    print("Python student")
    time.sleep(1)
    print("Він ледащо. ")
    time.sleep(1)
    print("Пунктуальність : 0%")
    time.sleep(1)
    print("Щирість : 0%")
    time.sleep(1)
    print("Дата народження: 04.12.2004")
    time.sleep(1)
    print("це все")
